
package via56.slickGenerator.crud.react

import via56.slickGenerator._
import via56.slickGenerator.Table

case class ReactFormGenerator(table: Table, tablesOneToMany: List[Table] = List(), submodulePackageString: String) extends CodeGenerator{

  def generateInputs(columns: List[AbstractColumn], prefix: String = ""): String = {
    val groupTab = (" "*10)
    val tab = (" "*12)
    val ref = (name: String) => s"""ref={(input) => this._inputs["${name}"] = input}"""
    columns.map{ col => col match{
      case c: Column if !c.synthetic && c.display != DisplayType.Hidden =>
        val input = if(c.isId) /* The ID is going to be autogenerated */
          tab+s"""<HiddenField ${ref(c.name)} name="${c.name}" defaultValue={obj.${c.name} || ""} readOnly={this.state.readOnly} />"""
        else
          tab+c.formHelperReact(prefix)
        groupTab+"<div>\n"+input+"\n"+groupTab+"</div>"
      case s: SubClass => throw new Exception("Subclas")//generateInputs(s.cols, s.name+".")
      case o: OneToMany => o.formHelper(submodulePackageString)
      case _ => ""
    }}.mkString("\n")
  }
  def generateOneToMany: String ={

  }

  def generate: String = {
    val imports = """import React from 'react';
import TextField from '../gforms/GTextField';
import HiddenField from '../gforms/GHiddenField';
import GForm from '../gforms/GForm';
//inputs de nested
"""
    val inputs = generateInputs(table.columns)
    val oneToMany = if(tablesOneToMany.length>0) generateOneToMany else ""
    val result =
      s"""$imports

/*
<Route path="/${table.objName}/new" component={${table.className}Form} />
<Route path="/${table.objName}/:id" component={${table.className}Form} />
<Route path="/${table.objName}/:page/:pageLength" component={${table.className}Form} />
*/
export default class ${table.className}Form extends GForm{
    showUrl =  '/${table.tableName}/'
    apiGetUrl =  '/${table.tableName}/show/'
    apiCreateUrl = '/${table.tableName}/save'
    apiUpdateUrl = '/${table.tableName}/update/'

    objStr = '${table.className}'
    objGender = 'F'

    renderForm(obj, errors){
        return <div>
${inputs}
        </div>
    }

}
${oneToMany}
      """
    result

  }
}
